- include: preprocess.yaml

- hosts: localhost
  gather_facts: no

  tasks:
    - include_vars: common_vars.yml

    # TODO: exclude Quicklisp, see:
    # https://www.darkchestnut.com/2016/dont-put-quicklisp-in-your-binary-just-because-a-library-demands-it/
    # https://www.darkchestnut.com/2016/keep-quicklisp-and-qlot-out-of-your-application-binary/
    - name: build webserver binary
      shell: "sbcl --eval \"(ql:quickload 'mentat-webserver)\" --eval \"(mentat-webserver::save-image-webserver)\""

- hosts: botservers
  gather_facts: no

  tasks:
    - include_vars: common_vars.yml

    - name: remove old webserver remote binary
      file:
        path=/home/{{ username }}/{{ webserver_binary_name }}
        state=absent

    - name: copy compiled webserver binary to remote server
      copy: src=../deploy/{{ webserver_binary_name }} dest=/home/{{ username }}

    - name: set webserver binary attrs
      file: path=/home/{{ username }}/{{ webserver_binary_name }} mode=u+rwx

    - name: restart mentat-webserver service on remote server
      supervisorctl: name=mentat-webserver state=restarted
      become: yes

- hosts: localhost

  tasks:
    - name: cleanup recently built binary
      file: path=./mentat-webserver state=absent

- include: postprocess.yaml
